# Generated by Django 3.1.6 on 2021-02-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('paciente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nasc', models.DateTimeField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=80, null=True)),
                ('endereco_num', models.CharField(blank=True, max_length=10, null=True)),
                ('endereco_bairro', models.CharField(blank=True, max_length=60, null=True)),
                ('cep', models.CharField(blank=True, max_length=100, null=True)),
                ('cadastro_date', models.DateTimeField(auto_now_add=True)),
                ('rg', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'pacientes',
                'managed': True,
            },
        ),
    ]
