# Generated by Django 3.1.6 on 2021-02-02 16:11

from django.db import migrations, models
import django.db.models.deletion
import imagens.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagensHistorico',
            fields=[
                ('imagem_historico_id', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=imagens.models.imagens_historico)),
                ('historico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='historicos.historicos')),
            ],
        ),
    ]
